-- CREATE DATABASE helmet_;

CREATE TABLE helmet (
    id INT PRIMARY KEY,
    name VARCHAR(16) NOT NULL,
    helmet BOOLEAN DEFAULT FALSE,
    image VARCHAR(12) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE action (
    id INT PRIMARY KEY,
    info VARCHAR(24) NOT NULL,
    action VARCHAR(4) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);